### ISSUE TITLE
FiberError: Cannot Resume a Fiber That Is Not Suspended with reactphp-redis During High Concurrency

### ISSUE THREAD

**Issue by pfk84** [clue/reactphp-redis#159] opened 2024-09-17 14:54 UTC
I’m not sure if this issue is specifically related to this library or ReactPHP, but currently, it only occurs with reactphp-redis.

When I run something like:

`$counter = await($this->redis->eval(self::LUA_SCRIPT, 1, $uri, $period));`

During periods of high concurrency, I encounter the following error:

`Unhandled promise rejection with FiberError: Cannot resume a fiber that is not suspended in /app/vendor/react/async/src/SimpleFiber.php:28`

Do you have any insights into why this is happening or what I could do to resolve it? Interestingly, when I work with the promises directly, everything functions correctly.

**Comment by pfk84** [comment] 2024-10-18 15:37
No idea? :( Pretty sure it's due to the eval... Other commands just work fine.

**Comment by clue** [comment] 2024-12-28 11:55
@pfk84 Thank you for reporting, this definitely should not have happened!

Unfortunately, this is somewhat hard if not impossible to trace unless we have reproducible code that shows this is related to this project. Currently, I don't see anything that would cause this kind of error in this project and have no reason to believe this would be caused by anything related to the `EVAL` Redis command, as this project doesn't really employ any special handling for individual Redis commands.

In the past, we've seen some similar reports in https://github.com/friends-of-reactphp/mysql/issues/123#issuecomment-1221368431 and https://github.com/reactphp/async/issues/50#issuecomment-1776901369 that all boiled down to incorrect usage of `async()`/`await()`, so this might be something worth investigating.

I understand this may be frustrating, but as much as I'd love to help, I'm sure you understand this would be out of scope for this project on its own. If you need more personalized help for a commercial project, please shoot me an email and I'm happy to take a look at this together with you. Likewise, if you can reproduce this and reply with a public gist, I'm happy to take a look at this when time allows.

I hope this helps! :+1: If so, consider supporting this project, for example by [becoming a sponsor](https://github.com/sponsors/clue) ❤️

**Closed as completed by clue** 2024-12-28 11:55 UTC
Labels: question
